name: Node.js CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: Inspect short sha
      id: get_short_sha
      run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
    - name: On master push, deploy to Cloudflare Workers with Wrangler
      if: github.ref == 'refs/heads/main'
      uses: cloudflare/wrangler-action@1.3.0
      env:
        BATTLESNAKE_VERSION: ${{ steps.get_short_sha.outputs.short_sha }}
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: production
        secrets: |
          BATTLESNAKE_VERSION
        postCommands: |
          set -o xtrace
          curl https://api.honeycomb.io/1/markers/tohu-battlesnake-pat-rapp -X POST -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_KEY }}" -d '{"message":"${{ env.BATTLESNAKE_VERSION }}", "type":"deploy"}'
